db:
  dialect: 'postgresql'
  host: 'host.database.com'
  user: 'username'
  password: 'password'
  database: 'database_name'
  port: 5432 #This is the default port for postgresql

logger:
  uri: 'mongodb://YOUR-MONGO-URI'
  db: 'YOUR-MONGO-DB-NAME'
  collection: 'YOUR-MONGO-DB-COLLECTION'
