##################################################################
#                    DSSG Team Cincinnati                        #
#                      Model Experiments                         #
##################################################################

# Temporal stuff
#start_date: '01Jan2008'    #train only on inspections after this date
fake_today: '01Apr2014'
validation_window: '1Year'  # Or '1Month'

# Generate full parcel predictions for Cincinnati
# Turn on after model validation/evaluation is complete
prepare_field_test: False
inspection_date: '01Aug2015'

# only use residential parcels
residential_only: True

############################
# Feature selection        #
############################

#New syntax for feature selection
#Syntax is used in a LIKE statement
features:
    #All columns on crime table
    - crime.%
    #single family column on house type
    - house_type.single-family
    #columns starting with rate in the census_2010 table
    - census_2010.rate2_%

############################
# Model selection          #
############################

#See grid_values.py for supported models
model: 'sklearn.ensemble.RandomForestClassifier'

############################
# Output                   #
############################

#Note that directories are relative to $OUTPUT_FOLDER
#This will be used if model.py has been configured to save results using PICKLE prepare_field_test
#see model.py for details
pkl_prefix: 'modelresult_'  # prefix model result with string
