##################################################################
#                    DSSG Team Cincinnati                        #
#                      Model Experiments                         #
##################################################################

# Temporal stuff
#start_date: '01Jan2008'    #train only on inspections after this date
fake_today: '01Apr2014'
validation_window: '1Year'  # Or '1Month'

# Generate full parcel predictions for Cincinnati
# Turn on after model validation/evaluation is complete
prepare_field_test: False
inspection_date: '01Aug2015'

# only use residential parcels
residential_only: True

############################
# Feature selection        #
############################

#List features to use, follow the syntax table.column where column
#is used in a LIKE statement
#http://www.postgresql.org/docs/current/static/functions-matching.html
features:
    #- crime.%
    - house_type.single-family
    - census_2010.rate_%

############################
# Model selection          #
############################

#See grid_values.py for supported models
#Use valid scikit-learn classes, provide the full path to the class
models:
  - 'sklearn.ensemble.AdaBoostClassifier'
 # - 'sklearn.ensemble.RandomForestClassifier'

#For each model you select, the pipeline will
#train a bunch of models, see grid_values for more
grid_size: 'small' #small, medium or big

############################
# Output                   #
############################

#Note that directories are relative to $OUTPUT_FOLDER
#This will be used if model.py has been configured to save results using PICKLE prepare_field_test
#see model.py for details
pkl_prefix: 'modelresult_'  # prefix model result with string
